title: rpi-scratch-add-pi-sense-hat
hero_image: images/banner.png
description: rpi-scratch-add-pi-sense-hat description
version: 4
listed: false
copyedit: false
last_tested: "2018-05-29"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
