title: Adding the Pi GPIO extension in Scratch
hero_image: images/banner.png
description: How to add the Pi GPIO extension in Scratch 2
original_url: 
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - title: Addding the Scratch Pi GPIO extension

